#!/bin/bash
set -e

# format shell scripts
shfmt -w -l .
shfmt -w -l immunity-monitoring/files/monitoring.agent
shfmt -w -l immunity-monitoring/files/monitoring.init
shfmt -w -l immunity-monitoring/files/immunity-monitoring.hotplug

# format lua files
cd immunity-monitoring/
lua-format -i --config=luaformat.config \
	files/sbin/*.lua \
	files/lib/immunity-monitoring/*.lua \
	tests/*.lua \
	tests/test_files/*.lua
